### ISSUE TITLE
Correção da iteração 0

### ISSUE THREAD

**Issue by ps1312** [IF977/MedicalHelp-Recife#10]
## Histórias de usuário:

* Formato -> ok
* História bem escrita -> ok
### nota final: 10
--------------------------------------------------------------------------------------------------------------
## Ata de reunião:
* Participantes da reunião -> ok
* Tópicos discutidos -> ok
* O que foi definido -> ok
* Formato Markdown -> ok
### nota final: 10
--------------------------------------------------------------------------------------------------------------
## Mockups e storyboards:
* Mockups -> ok
* Storyboard -> ok
### nota final: 10
--------------------------------------------------------------------------------------------------------------
## Preenchimento do GitHub:
* Nome do projeto -> ok
* Descrição do projeto -> 
&nbsp;&nbsp; -Problema bem descrito: O hospital que será indicado obedece a um range dentro do mapa?, -1
&nbsp;&nbsp; -Publico alvo: Lendo a descrição do projeto o usuário só seria o paciente, porém de acordo com as histórias de usuário as testemunhas também seriam usuários, -1
* Justificativa do projeto -> ok
* Especificação do papel dos membros -> ok
### nota final: 8
--------------------------------------------------------------------------------------------------------------
## Postmortem
* O que estava planejado -> ok
* Listar as atividades que foram planejadas para a alteração e o responsável por cada uma delas -> ok
* O que foi feito -> ok
* O que não foi feito -> ok
* O que está planejado pra próxima iteração -> ok
* Lições aprendidas -> ok
* Formato Markdown -> ok
> Tentem dividir mais os responsáveis ao invés de colocar muitos "Todos". Nesse caso, a união não faz a força.
### nota final: 10
--------------------------------------------------------------------------------------------------------------
### Observações finais:
> Pessoal, sempre criem as issues no começo das iterações. Além de dar mais tempo para corrigir o erro a criação no início também vai contar ponto nas próximas iterações.

**Comment by meugenia1** [comment]
Monitor, os storyboards foram esboçados de maneira sequencial usando as
próprias páginas do .pdf upado.

Em 27 de setembro de 2017 09:39, ps1312 <notifications@github.com> escreveu:
