### ISSUE TITLE
Feedback Cadastrar histórias no gitHub IT2 

### ISSUE THREAD

**Issue by lsca** [IF977/MedicalHelp-Recife#46]
Eai galera, tudo certinho??

- Uso de lable : OK
- Milestones : OK
- 1 Issue por participante : OK
- Descrição da issue : -0,4.

**Com relação a descrição das issues, tentem ser mais descritivos.**

Ex:
Issue -> (Popular banco de dados #42)
Descrição -> Popular banco de dados com dados dos hospitais.
Parece redundante não?

Podiam colocar o que falta popular, como será feito. Assim como foi feito na issue "Criação de testes rspec #35" em que vocês colocaram o que seria testado.

Qualquer duvida só falar aqui. Caso concordem, só fechar a issue.

**Comment by lsca** [comment]
Corrigindo só uma coisa.

**- 1 Issue por participante : OK**

**Comment by gmenge** [comment]
Obrigado pelo feedback, meu velho!
