### ISSUE TITLE
FeedBack dos testes de TDD e BDD - Iteração 02

### ISSUE THREAD

**Issue by ps1312** [IF977/MedicalHelp-Recife#49]
## Testes BDD:

* Não possui nenhum caminho triste -> -1
* Todos os testes verdes -> Não, o seguinte teste não passou. -1

![image](https://user-images.githubusercontent.com/19872825/31998989-7c00e9ae-b970-11e7-85cf-d96d404d1dda.png)

## Testes TDD:

* Não possuem caminhos tristes -> -1
* Todos os testes verdes -> Sim, tudo certo

> Galera, os arquivos que vocês não forem implementar
(MedicalHelp-Recife/spec/models/hospital_spec.rb por exemplo)
vocês podem deletar para não causar nenhuma confusão.

#### Nota BDD: 4
---
## nota final: 7

**Comment by meugenia1** [comment]
Monitor, o teste falhou porque a funcionalidade ainda não foi implementada,
mas o teste está correto.

**Comment by ps1312** [comment]
Mas os testes não foram verdes, pra eles serem verdes (passarem) as funcional

**Comment by ps1312** [comment]
As funcion

**Comment by ps1312** [comment]
Foi mal abrir e fechar duas vezes. Mas pra os testes passarem as funcionalidades precisam ser implementadas, por isso eu n dei a nota máxima pra vocês, na sintaxe os testes tão corretos mas eles precisam passar pra valer a nota máxima.

**Comment by ps1312** [comment]
Galera, só pra deixar mais explicado: Certamente que os testes devem ser escritos antes da implementação da feature porém eles devem ser escritos na mesma iteração, a implementação de uma feature que já possui o teste não pode ficar para uma próxima, é necessário seguir o ciclo de vida da iteração:

![image](https://user-images.githubusercontent.com/19872825/32498547-1dd3eb32-c3b7-11e7-8766-2deba838354b.png)
Ciclo de vida de uma iteração de acordo com o livro texto adotado.

![image](https://user-images.githubusercontent.com/19872825/32498577-35dcec4c-c3b7-11e7-9169-344f2be047e4.png)
Ciclo de vida da etapa de teste de acordo com os slides da disciplina
